development:
  cloud_name: taake
  api_key: '548146482323371'
  api_secret: 0h9usS7_ia7dFQaW26u7oXWfjRQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: taake
  api_key: '548146482323371'
  api_secret: 0h9usS7_ia7dFQaW26u7oXWfjRQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: taake
  api_key: '548146482323371'
  api_secret: 0h9usS7_ia7dFQaW26u7oXWfjRQ
  enhance_image_tag: true
  static_image_support: false
